version: "3.8"
services:
    postgres:
        image: "postgres:13"
        ports:
            - "5435:5432"
        environment:
            - POSTGRES_DB=bowman
            - POSTGRES_USER=bowman
            - POSTGRES_PASSWORD=bowman
    web:
        depends_on:
            - postgres
        build: .
        ports:
            - "8080:8080"
        environment:
            - PGHOST=postgres
            - PGPORT=5432
            - PGDATABASE=bowman
            - PGUSER=bowman
            - PGPASSWORD=bowman
