---
- name: Install certbot
  apt:
    name:
      - certbot
      - python3-certbot-nginx
    state: present
    update_cache: true

- name: Obtain SSL certificate
  command: >
    certbot certonly --nginx
    -d {{ domain }}
    --non-interactive
    --agree-tos
    --email {{ certbot_email }}
  args:
    creates: /etc/letsencrypt/live/{{ domain }}/fullchain.pem
